name: Development Builds

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11
      options: --user root --workdir /usr/src/firmware
    steps:
      - uses: actions/checkout@v3

      - name: Get dependencies
        run: "apt-get update && apt-get install -y make curl && curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh"

      - name: Build
        run: make build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: firmware-hex
          path: dist/
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download firmware-hex
        uses: actions/download-artifact@v3
        with:
          name: firmware-hex
          path: dist/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest build on develop"
          files: |
            dist/*.hex
